// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "4c38fd13-e407-4da6-a7b2-a04346af8943";
        public const string Name = "Extensibility Essentials 2022";
        public const string Description = @"A collection of extensions that makes it much easier to write Visual Studio extensions";
        public const string Language = "en-US";
        public const string Version = "1.1.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, vsx, extensibility";
    }
}
