// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityEssentials
{
    internal sealed partial class Vsix
    {
        public const string Id = "f613e37-c9b4-4e49-b61f-0cf036ca76d6";
        public const string Name = "Extensibility Essentials 2017";
        public const string Description = @"A collection of extensions that makes it much easier to write Visual Studio extensions";
        public const string Language = "en-US";
        public const string Version = "1.1.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vsix, vsx, extensibility";
    }
}
